const celebrityData = [
    {
        id: "amal-clooney",
        name: "Amal Clooney",
        birthday: "02-03",
        sun: "Aquarius",
        moon: "Sagittarius",
        ascendant: "Aquarius",
        image: "",
        bio: "Human rights lawyer, activist, and style icon known for her international legal work.",
        link: "../reference/celebrity/amal-clooney.html",
        exists: true
    },
    {
        id: "shakira",
        name: "Shakira",
        birthday: "02-02",
        sun: "Aquarius",
        moon: "Cancer",
        ascendant: "Aries",
        image: "../images/celebrity/shakira.jpg",
        bio: "Global music superstar known for her unique voice and dance moves.",
        link: "../reference/celebrity/shakira.html",
        exists: true
    },
    {
        id: "harry-styles",
        name: "Harry Styles",
        birthday: "02-01",
        sun: "Aquarius",
        moon: "Libra",
        ascendant: "Libra",
        image: "../images/celebrity/harry-styles.jpg",
        bio: "Singer, songwriter, and actor known for his fashion and musical versatility.",
        link: "../reference/celebrity/harry-styles.html",
        exists: true
    },
    {
        id: "cristiano-ronaldo",
        name: "Cristiano Ronaldo",
        birthday: "02-05",
        sun: "Aquarius",
        moon: "Leo",
        ascendant: "Capricorn",
        image: "../images/celebrity/ronaldo.jpg",
        bio: "One of the greatest footballers of all time, known for his incredible work ethic and ambition.",
        link: "../reference/celebrity/cristiano-ronaldo.html",
        exists: true
    },
    {
        id: "bob-marley",
        name: "Bob Marley",
        birthday: "02-06",
        sun: "Aquarius",
        moon: "Scorpio",
        ascendant: "Sagittarius",
        image: "../images/celebrity/bob-marley.jpg",
        bio: "Reggae pioneer and global icon who spread a message of love, unity, and social justice.",
        link: "../reference/celebrity/bob-marley.html",
        exists: true
    },
    {
        id: "oprah-winfrey",
        name: "Oprah Winfrey",
        birthday: "01-29",
        sun: "Aquarius",
        moon: "Sagittarius",
        ascendant: "Sagittarius",
        image: "../images/celebrity/oprah.jpg",
        bio: "Media mogul, talk show host, actress, and philanthropist.",
        link: "../reference/celebrity/oprah-winfrey.html",
        exists: true
    },
    {
        id: "david-bowie",
        name: "David Bowie",
        birthday: "01-08",
        sun: "Capricorn",
        moon: "Leo",
        ascendant: "Aquarius",
        image: "../images/celebrity/bowie.jpg",
        bio: "Legendary musician and actor, known for his reinvention and visual style.",
        link: "../reference/celebrity/david-bowie.html",
        exists: true
    },
    {
        id: "lady-gaga",
        name: "Lady Gaga",
        birthday: "03-28",
        sun: "Aries",
        moon: "Scorpio",
        ascendant: "Gemini",
        image: "../images/celebrity/gaga.jpg",
        bio: "Singer, songwriter, and actress known for her image reinventions and vocal power.",
        link: "../reference/celebrity/lady-gaga.html",
        exists: true
    },
    {
        id: "frida-kahlo",
        name: "Frida Kahlo",
        birthday: "07-06",
        sun: "Cancer",
        moon: "Taurus",
        ascendant: "Leo",
        image: "../images/celebrity/kahlo.jpg",
        bio: "Mexican painter known for her many portraits, self-portraits, and works inspired by the nature and artifacts of Mexico.",
        link: "../reference/celebrity/frida-kahlo.html",
        exists: true
    },
    {
        id: "donald-trump",
        name: "Donald Trump",
        birthday: "06-14",
        sun: "Gemini",
        moon: "Sagittarius",
        ascendant: "Leo",
        image: "../images/celebrity/trump.jpg",
        bio: "45th U.S. President, businessman, and media personality.",
        link: "../reference/celebrity/donald-trump.html",
        exists: true
    },
    {
        id: "prince",
        name: "Prince",
        birthday: "06-07",
        sun: "Gemini",
        moon: "Pisces",
        ascendant: "Scorpio",
        image: "../images/celebrity/prince.jpg",
        bio: "Musician, singer, songwriter, record producer, dancer, and actor.",
        link: "../reference/celebrity/prince.html",
        exists: true
    },
    {
        id: "beyonce",
        name: "Beyoncé",
        birthday: "09-04",
        sun: "Virgo",
        moon: "Scorpio",
        ascendant: "Libra",
        image: "../images/celebrity/beyonce.jpg",
        bio: "Singer, songwriter, and actress. Known as 'Queen Bey', she has been major figure in popular culture.",
        link: "../reference/celebrity/beyonce.html",
        exists: true
    },
    {
        id: "drake",
        name: "Drake",
        birthday: "10-24",
        sun: "Scorpio",
        moon: "Cancer",
        ascendant: "Leo",
        image: "../images/celebrity/drake.jpg",
        bio: "Rapper, singer, songwriter, actor, and entrepreneur.",
        link: "../reference/celebrity/drake.html",
        exists: true
    },
    {
        id: "leonardo-dicaprio",
        name: "Leonardo DiCaprio",
        birthday: "11-11",
        sun: "Scorpio",
        moon: "Libra",
        ascendant: "Libra",
        image: "../images/celebrity/leo.jpg",
        bio: "Actor and film producer. Known for his work in biopics and period films.",
        link: "../reference/celebrity/leonardo-dicaprio.html",
        exists: true
    },
    {
        id: "taylor-swift",
        name: "Taylor Swift",
        birthday: "12-13",
        sun: "Sagittarius",
        moon: "Cancer",
        ascendant: "Scorpio",
        image: "../images/celebrity/taylor.jpg",
        bio: "Singer-songwriter known for narrative songs about her personal life.",
        link: "../reference/celebrity/taylor-swift.html",
        exists: true
    }
];
